[network]
remote='0.0.0.0'

[peripheral]
device='joystick'
periodic_trigger=false
sampling_time=0.5
timeout=2.0

[button_map_td]
neutral=1
reverse=0
emergency=2
forward=3
steer_left=4
steer_right=5

[button_map_kuka]
left=2
right=1
up=3
down=0

[command]
FORWARD="#FORWA@"
REVERSE="#NEUTR@"
NEUTRAL="#REVER@"

[message_id]
throttle_msgid="0016"
brake_msgid="0001"
steering_msgid="0017"
rf_msgid="0002"